# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         encoding-split
version:      0.02
version_from: lib/encoding/split.pm
installdirs:  site
requires:
    encoding::source:              0.02
    encoding::stdio:               0.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
